# Generated by Django 2.0.13 on 2020-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='param_ed',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
