# Generated by Django 2.0.13 on 2020-02-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200214_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
