# Generated by Django 2.0.13 on 2020-04-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_brief_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='problem_id',
            field=models.IntegerField(null=True, verbose_name='Номер задачи'),
        ),
    ]
